name: Hello World!

on:
  push:
    branches:
      - jopo

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - name: The job has succeeded
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,eventName,workflow,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        # if: always() # Pick up events even if the job fails or is canceled.
#     steps:
#       - uses: actions/checkout@v2
#       - name: gihub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: echo "$GITHUB_CONTEXT"
#       - name: commits
#         env:
#           COMMITS: ${{ toJson(github.event.commits) }}
#         run: echo "$COMMITS"
#       # - name: meessage
#       #   env:
#       #     MESSAGE: ${{ toJson(github.event.commits[0].message) }}
#       #   run: echo "$MESSAGE"
#       - name: commit messages
#         env:
#           COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
#         run: echo "$COMMIT_MESSAGES"
#       - name: onkoskippi
#         env:
#           MESSAGEX: ${{ toJson(github.event.commits.*.message) }}
#         if: ${{ !(contains(github.event.commits.*.message, '#skip')) }}
#         run: echo "$MESSAGEX"
#       - name: commit messages not skip? JOO
#         env:
#           COMMIT_MESSAGES_contains: ${{ !(contains(github.event.commits.*.message, '#skip')) }} 
#         run: echo "$COMMIT_MESSAGES_contains"  
      

# # jobs:
# #   hello_world_job:
# #     runs-on: ubuntu-18.04
# #     steps:
# #       - name: Say hello
# #         run: |
# #           echo "Hello World!"
        

#   # now_it_is_job:
#   #   runs-on: ubuntu-18.04
#   #   steps:
#   #     - name: Now it is
#   #       run: |
#   #         date

#   # directory_content:
#   #   runs-on: ubuntu-18.04
#   #   steps:
#   #     - name: Directory content
#   #       run: |
#   #         ls -l
